### ISSUE TITLE
[Question] which deployment to specify in the config

### ISSUE THREAD

**Issue by ghost** [pivotal-cf-experimental/datadog-config-oss#6]
Hello,

I found our bosh deployments by logging into the director on the bosh command line and doing this:

```
cfadmin@pivotal-ubuntu:~/datadogconfigoss/datadog-config-oss-master$ bosh deployments
Acting as user 'director' on 'microbosh-fd6868b53306451573eb'

+----------------------------------------------+-------------------------------+-------------------------------------------------+--------------+
| Name                                         | Release(s)                    | Stemcell(s)                                     | Cloud Config |
+----------------------------------------------+-------------------------------+-------------------------------------------------+--------------+
| cf-9f66ec3b92e86035c0a2                      | cf-autoscaling/28             | bosh-vsphere-esxi-ubuntu-trusty-go_agent/3146   | none         |
|                                              | cf-mysql/23                   |                                                 |              |
|                                              | cf/225.3                      |                                                 |              |
|                                              | diego/0.1441.1                |                                                 |              |
|                                              | etcd/18                       |                                                 |              |
|                                              | garden-linux/0.330.0          |                                                 |              |
|                                              | notifications-ui/10           |                                                 |              |
|                                              | notifications/19              |                                                 |              |
|                                              | push-apps-manager-release/397 |                                                 |
```

So I entered that information into the config file:

```
cf_deployment:
  deployment: "cf-9f66ec3b92e86035c0a2"
  bosh_deployment: "bosh"
  services_deployment: "cf-9f66ec3b92e86035c0a2-services"
  micro_deployment: "cf-micro-deployment-example"
  health_screen_image: "microbosh/0"
  router_elb_name: "cf-router"
  domain_url: "https://ops.pcf.example.com"
```

And from the datadog-config-oss-master directory I run the 'bundle install' command (which installs a bunch of gems) and then attempt to run the rake command which gives me: 

```
pcfadmin@pivotal-ubuntu:~/datadogconfigoss/datadog-config-oss-master$ rake  cf-9f66ec3b92e86035c0a2:push --trace
rake aborted!
Don't know how to build task 'cf-9f66ec3b92e86035c0a2:push' (see --tasks)
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/task_manager.rb:62:in `[]'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:149:in `invoke_task'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/bin/rake:23:in `load'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/bin/rake:23:in `<main>'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/home/pcfadmin/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

What am I doing wrong? And how can I get this command to execute correctly?

thanks

**Comment by bhudlemeyer** [comment]
This messed me up to 
top line cf_deployment:   === Deployment name

So you have to change that to make the name actually change for the rake command.

**Comment by pronoiac** [comment]
To clarify what @bhudlemeyer said: if you run `rake -T` you'll see your options: 

```
rake cf_deployment:console                               # A console with some useful variables
rake cf_deployment:delete_unknown                        # Delete dashboards and alerts that are not represented in local templates for Cf_deployment
rake cf_deployment:emit[metric]                          # emit data to datadog for testing purposes (note this WILL affect graphs and alerts)
rake cf_deployment:eval_alert[path]                      # Evaluate the alert at path under the Cf_deployment config and print to stdout
rake cf_deployment:eval_dashboard[path]                  # Evaluate the dashboard at path under the Cf_deployment config and print to stdout
rake cf_deployment:eval_screen[path]                     # Evaluate the screen at path under the Cf_deployment config and print to stdout
rake cf_deployment:get_alert_json_erb[alert_id,path]     # Make a json template for the specified alert at the given file path
rake cf_deployment:get_dashboard_json_erb[dash_id,path]  # Make a json template for the specified dashboard at the given file path
rake cf_deployment:get_screen_json_erb[screen_id,path]   # Make a json template for the specified screen at the given file path
rake cf_deployment:list_unknown                          # List dashboards and alerts that are not represented in local templates for Cf_deployment
rake cf_deployment:push                                  # Push Cf_deployment Datadog Config
```

I think you want `rake cf_deployment:push`, or to rename your deployment to something catchier. :smile:

**Comment by pronoiac** [comment]
No activity for two months; closing.
